name: superheroes
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  provider: ^6.0.5
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.1.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/images/
